-- Lyric Flow — Lyric Capital Group firm priorities dashboard
-- Run this once in Supabase: SQL Editor -> New query -> paste -> Run.

-- ============ tables ============
create table if not exists public.tasks (
  id text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.meta (
  key text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  person text
);

-- keep updated_at fresh
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists tasks_touch on public.tasks;
create trigger tasks_touch before update on public.tasks for each row execute function public.touch_updated_at();
drop trigger if exists meta_touch on public.meta;
create trigger meta_touch before update on public.meta for each row execute function public.touch_updated_at();

-- ============ row-level security ============
-- Only signed-in users can read or write anything. Sign-ups are created by
-- you in the Supabase console, so "authenticated" = your approved people.
alter table public.tasks enable row level security;
alter table public.meta enable row level security;
alter table public.profiles enable row level security;

drop policy if exists tasks_rw on public.tasks;
create policy tasks_rw on public.tasks for all to authenticated using (true) with check (true);
drop policy if exists meta_rw on public.meta;
create policy meta_rw on public.meta for all to authenticated using (true) with check (true);
drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ============ live sync ============
alter publication supabase_realtime add table public.tasks;
alter publication supabase_realtime add table public.meta;

-- ============ seed: Vault loaded from the 28 Sep 2026 Priority Register ============
insert into public.tasks (id, data) values ('v01', $json${"gid":"v01","name":"Alesso","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Closing","order":1,"subtasks":[{"gid":"v01s01","name":"Confirm closing (reported closing Thursday; overdue since 18 Sep) and clear","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v02', $json${"gid":"v02","name":"Tkay","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Closing · Songs of Spirit · longform","order":2,"subtasks":[{"gid":"v02s01","name":"Assign owner and drive to close","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v03', $json${"gid":"v03","name":"Will Jay","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Closing · Songs of Spirit · $275k advance with flowthrough","order":3,"subtasks":[{"gid":"v03s01","name":"Assign owner and drive to close","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v04', $json${"gid":"v04","name":"Project Ecosystem","lead":"Vinny","horizon":"vault","group":"Deals","dueDate":"2026-10-24","followUp":[],"note":"Exclusivity / diligence · Priority #1","order":4,"subtasks":[{"gid":"v04s01","name":"Run diligence to close","assignee":"Vinny","horizon":"vault","dueDate":"2026-10-24","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v05', $json${"gid":"v05","name":"All American Rejects","lead":"Abe","horizon":"vault","group":"Deals","dueDate":"2026-09-30","followUp":[],"note":"Exclusivity / diligence","order":5,"subtasks":[{"gid":"v05s01","name":"Respond to band on creative structure request","assignee":"Abe","horizon":"vault","dueDate":"2026-09-30","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v06', $json${"gid":"v06","name":"Playboi Carti","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Exclusivity / diligence · $50M+ · LOI outstanding","order":6,"subtasks":[{"gid":"v06s01","name":"Get LOI out","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v06s02","name":"Resolve status conflict on the board","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v07', $json${"gid":"v07","name":"Jonathan Cain (Journey)","lead":"Abe","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Exclusivity / diligence · Abraham & Mason","order":7,"subtasks":[{"gid":"v07s01","name":"Confirm 23 Sep completion was a close, not a pass","assignee":"Abe","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v08', $json${"gid":"v08","name":"Howe","lead":"Victor","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Exclusivity / diligence · RBN structure","order":8,"subtasks":[{"gid":"v08s01","name":"Monitor — nothing actionable at present","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v09', $json${"gid":"v09","name":"Angelo Mota","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Diligence · Songs of Spirit · sub-$10M","order":9,"subtasks":[{"gid":"v09s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v10', $json${"gid":"v10","name":"Taydex","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Diligence · Songs of Spirit · sub-$10M","order":10,"subtasks":[{"gid":"v10s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v11', $json${"gid":"v11","name":"Coleton Rubin","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Diligence · Songs of Spirit · sub-$10M","order":11,"subtasks":[{"gid":"v11s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v12', $json${"gid":"v12","name":"Southside","lead":"Abe","horizon":"vault","group":"Deals","dueDate":"2026-10-02","followUp":[],"note":"LOI · Abraham & Mason","order":12,"subtasks":[{"gid":"v12s01","name":"Finish one-pager","assignee":"Abe","horizon":"vault","dueDate":null,"done":false},{"gid":"v12s02","name":"Get overdue LOI to seller by Friday","assignee":"Abe","horizon":"vault","dueDate":"2026-10-02","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v13', $json${"gid":"v13","name":"Aerosmith","lead":"Abe","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · awaiting LOI from RS","order":13,"subtasks":[{"gid":"v13s01","name":"Chase LOI from RS — this-week priority","assignee":"Abe","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v14', $json${"gid":"v14","name":"Lil Baby","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · $50M+ · one-pager presented","order":14,"subtasks":[{"gid":"v14s01","name":"Next step after one-pager","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v14s02","name":"Resolve status conflict on the board","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v15', $json${"gid":"v15","name":"Tommy Brown","lead":"Abe","horizon":"vault","group":"Deals","dueDate":"2026-11-01","followUp":[],"note":"LOI · existing LOI expires 31 Oct","order":15,"subtasks":[{"gid":"v15s01","name":"Diary: engage after existing LOI expires","assignee":"Abe","horizon":"vault","dueDate":"2026-11-01","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v16', $json${"gid":"v16","name":"Empire (Ghazi)","lead":"Victor","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI","order":16,"subtasks":[{"gid":"v16s01","name":"Progress LOI","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v17', $json${"gid":"v17","name":"CRM (Neil Gillis)","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · structure discussion with PG pending","order":17,"subtasks":[{"gid":"v17s01","name":"Structure discussion with PG","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v18', $json${"gid":"v18","name":"Randy Montana","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · Lyric and Songs of Spirit offers both out 15 Sep","order":18,"subtasks":[{"gid":"v18s01","name":"Chase both offers","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v19', $json${"gid":"v19","name":"Tim McGraw","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · unassigned","order":19,"subtasks":[{"gid":"v19s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v20', $json${"gid":"v20","name":"Nic Hooper","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · unassigned","order":20,"subtasks":[{"gid":"v20s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v21', $json${"gid":"v21","name":"Gustavo Santaolalla","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · unassigned","order":21,"subtasks":[{"gid":"v21s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v22', $json${"gid":"v22","name":"Five Finger Death Punch","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · unassigned","order":22,"subtasks":[{"gid":"v22s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v23', $json${"gid":"v23","name":"Derek George","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · unassigned","order":23,"subtasks":[{"gid":"v23s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v24', $json${"gid":"v24","name":"Ratchopper","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · unassigned","order":24,"subtasks":[{"gid":"v24s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v25', $json${"gid":"v25","name":"Noam Daniel / Jeremy Zag","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · MMM 2.0 name · James Gibb sourced · pending time-allocation decision","order":25,"subtasks":[{"gid":"v25s01","name":"Assign or park","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v26', $json${"gid":"v26","name":"Paw Patrol","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · MMM 2.0 name · pending time-allocation decision","order":26,"subtasks":[{"gid":"v26s01","name":"Assign or park","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v27', $json${"gid":"v27","name":"Guillaume Roussel","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · MMM 2.0 name · pending time-allocation decision","order":27,"subtasks":[{"gid":"v27s01","name":"Assign or park","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v28', $json${"gid":"v28","name":"Christophe Beck","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"LOI · MMM 2.0 name · pending time-allocation decision","order":28,"subtasks":[{"gid":"v28s01","name":"Assign or park","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v29', $json${"gid":"v29","name":"Dominance MMA","lead":"Victor","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model complete · overdue since 31 Jul · kill candidate","order":29,"subtasks":[{"gid":"v29s01","name":"Staff Menachem for remaining work this week, or move to Passed","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v30', $json${"gid":"v30","name":"Jim Alexander","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model complete · term sheet out · Frank met the UK team","order":30,"subtasks":[{"gid":"v30s01","name":"Progress term sheet","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v31', $json${"gid":"v31","name":"Johnny Valentine","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model complete · term sheet back and forth","order":31,"subtasks":[{"gid":"v31s01","name":"Close out term sheet negotiation","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v32', $json${"gid":"v32","name":"Federation Studio","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model complete · MMM · reviewing model","order":32,"subtasks":[{"gid":"v32s01","name":"Assign owner and finish model review","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v33', $json${"gid":"v33","name":"Rupert Parkes","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model complete · MMM · reviewing model","order":33,"subtasks":[{"gid":"v33s01","name":"Assign owner and finish model review","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v34', $json${"gid":"v34","name":"Graeme Revell","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model complete · MMM · reviewing model","order":34,"subtasks":[{"gid":"v34s01","name":"Assign owner and finish model review","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v35', $json${"gid":"v35","name":"Daniel Ross","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model complete · unassigned","order":35,"subtasks":[{"gid":"v35s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v36', $json${"gid":"v36","name":"Martin Garrix","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model underway · $50M+","order":36,"subtasks":[{"gid":"v36s01","name":"Get remaining data from Martin's father","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v36s02","name":"Prepare two offers: catalogue buyout and 360 structure","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v37', $json${"gid":"v37","name":"Tape Room (Ashley Gorley)","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":"2026-09-29","followUp":[],"note":"Model underway · ShotTower process · offer expected mid-October","order":37,"subtasks":[{"gid":"v37s01","name":"Prepare for ShotTower process","assignee":"Thomas","horizon":"vault","dueDate":"2026-09-29","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v38', $json${"gid":"v38","name":"Benson Boone","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model underway · awaiting statement data","order":38,"subtasks":[{"gid":"v38s01","name":"Obtain statement data from sellers","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v39', $json${"gid":"v39","name":"Bert Burns","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model underway · unassigned","order":39,"subtasks":[{"gid":"v39s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v40', $json${"gid":"v40","name":"Roberto Carlos","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model underway · unassigned","order":40,"subtasks":[{"gid":"v40s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v41', $json${"gid":"v41","name":"John Shanks","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Model underway · unassigned","order":41,"subtasks":[{"gid":"v41s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v42', $json${"gid":"v42","name":"Dominic Fike","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · one-pager overdue since 23 Sep · Sal pushing","order":42,"subtasks":[{"gid":"v42s01","name":"Deliver one-pager","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v42s02","name":"Collect Sony JV statement at month end","assignee":"Thomas","horizon":"vault","dueDate":"2026-09-30","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v43', $json${"gid":"v43","name":"Imagine Dragons","lead":"Ross","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · $50M+ RBN/equity · joint RC/Vineel · drifting since 31 Jul","order":43,"subtasks":[{"gid":"v43s01","name":"Restart one-pager and data request","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v44', $json${"gid":"v44","name":"David Guetta","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · $50M+ · awaiting diligence materials","order":44,"subtasks":[{"gid":"v44s01","name":"Chase diligence materials","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v45', $json${"gid":"v45","name":"Fairuz","lead":"Victor","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · Raine running process · expected to ramp","order":45,"subtasks":[{"gid":"v45s01","name":"Speak to sellers","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v46', $json${"gid":"v46","name":"Future","lead":"Abe","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · data room received but incomplete","order":46,"subtasks":[{"gid":"v46s01","name":"Complete one-pager","assignee":"Abe","horizon":"vault","dueDate":null,"done":false},{"gid":"v46s02","name":"Call with Future's mother","assignee":"Abe","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v47', $json${"gid":"v47","name":"London on Da Track","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · data received · not staffed · Alan rates the producer highly","order":47,"subtasks":[{"gid":"v47s01","name":"Staff it or park it explicitly","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v47s02","name":"Start income summary","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v48', $json${"gid":"v48","name":"Mike Dean","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · data room expected this week · no owner","order":48,"subtasks":[{"gid":"v48s01","name":"Assign owner","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v48s02","name":"Review data room on arrival","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v49', $json${"gid":"v49","name":"Black River / Ballerini","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · wants to partner with Big Loud · three board records","order":49,"subtasks":[{"gid":"v49s01","name":"Big Loud partnership approach","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v49s02","name":"De-duplicate the three board records","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v50', $json${"gid":"v50","name":"Top Dawg Entertainment","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · Kendrick Lamar, SZA · NDA stage · unowned","order":50,"subtasks":[{"gid":"v50s01","name":"Assign owner","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v51', $json${"gid":"v51","name":"UAM (Universal Arabic Music)","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · no action until data arrives · ramp candidate","order":51,"subtasks":[{"gid":"v51s01","name":"Review on data arrival","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v52', $json${"gid":"v52","name":"Buffalo Bills","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · awaiting NDA signature · no prior record","order":52,"subtasks":[{"gid":"v52s01","name":"Await NDA signature, then kick off","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v53', $json${"gid":"v53","name":"Live Nation Merchandising","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · call with Matt Hansen being scheduled · SalxCo adjacency","order":53,"subtasks":[{"gid":"v53s01","name":"Game plan before the call","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v53s02","name":"Schedule Matt Hansen call","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v54', $json${"gid":"v54","name":"Pulse","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · direction needed · no prior record","order":54,"subtasks":[{"gid":"v54s01","name":"Set direction","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v55', $json${"gid":"v55","name":"The Shalizi Group","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · one-pager stage · unassigned","order":55,"subtasks":[{"gid":"v55s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v56', $json${"gid":"v56","name":"Koe Wetzel","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · one-pager stage · unassigned","order":56,"subtasks":[{"gid":"v56s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v57', $json${"gid":"v57","name":"Wu Tang Clan","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · one-pager stage · unassigned","order":57,"subtasks":[{"gid":"v57s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v58', $json${"gid":"v58","name":"Travis Scott","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · awaiting diligence materials · unassigned","order":58,"subtasks":[{"gid":"v58s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v59', $json${"gid":"v59","name":"Chief Keef","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · awaiting diligence materials · unassigned","order":59,"subtasks":[{"gid":"v59s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v60', $json${"gid":"v60","name":"Swedish House Mafia","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · awaiting diligence materials · unassigned","order":60,"subtasks":[{"gid":"v60s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v61', $json${"gid":"v61","name":"John Williams","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · awaiting diligence materials · unassigned","order":61,"subtasks":[{"gid":"v61s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v62', $json${"gid":"v62","name":"Toby McKeehan","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · awaiting diligence materials · unassigned","order":62,"subtasks":[{"gid":"v62s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v63', $json${"gid":"v63","name":"Big Noise","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · awaiting diligence materials · unassigned","order":63,"subtasks":[{"gid":"v63s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v64', $json${"gid":"v64","name":"Rezonate","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Early stage · awaiting diligence materials · unassigned","order":64,"subtasks":[{"gid":"v64s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v65', $json${"gid":"v65","name":"United Masters","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Kill candidate · duplicated on the board","order":65,"subtasks":[{"gid":"v65s01","name":"Decide kill or keep, then archive both duplicate records","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v66', $json${"gid":"v66","name":"Ink Entertainment","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"note":"Killed","order":66,"subtasks":[{"gid":"v66s01","name":"Send the note explaining why","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v67', $json${"gid":"v67","name":"SalxCo / YCFU","lead":"Ross","horizon":"vault","group":"Deals","dueDate":"2026-10-15","followUp":[],"note":"Exclusivity · RC critical path · items clustered 9–15 Oct","order":67,"subtasks":[{"gid":"v67s01","name":"RBN / debt financing structure (run bridge loan as the same item)","assignee":"Ross","horizon":"vault","dueDate":"2026-10-09","done":false},{"gid":"v67s02","name":"Third-party partnerships — Live Nation reorg + documentation","assignee":"Ross","horizon":"vault","dueDate":"2026-10-14","done":false},{"gid":"v67s03","name":"Contracts operating outside of term — Weeknd/Brandy/Metro memorialisation","assignee":"Ross","horizon":"vault","dueDate":"2026-10-14","done":false},{"gid":"v67s04","name":"Draft management agreements for potential signings (Young Thug, Future, Rema, M.I.A.)","assignee":"Ross","horizon":"vault","dueDate":"2026-10-14","done":false},{"gid":"v67s05","name":"Artist contract diligence","assignee":"Ross","horizon":"vault","dueDate":"2026-10-15","done":false},{"gid":"v67s06","name":"Pre-closing reorganization legal & tax sign-off","assignee":"Abe","horizon":"vault","dueDate":"2026-09-30","done":false},{"gid":"v67s07","name":"Employee & corporate structure chart (D&O list from GSM)","assignee":"Rich","horizon":"vault","dueDate":"2026-09-29","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v68', $json${"gid":"v68","name":"Pipeline hygiene","lead":"Vinny","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"Deal board clean-up","order":68,"subtasks":[{"gid":"v68s01","name":"'Deal Identified' backlog (~40 names untouched since May migration) — archive or set review dates","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v69', $json${"gid":"v69","name":"Recruiting","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"","order":69,"subtasks":[{"gid":"v69s01","name":"Senior Fund Accountant — agree Claude screening prompt (Rich/RC), then review 80 resumes","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s02","name":"FP&A Associate — resume review (same blocker)","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s03","name":"Analyst hire — set date and plan","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s04","name":"COO/CFO (Sean Pallen) — confirm offer letter status","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s05","name":"Sean Pallen — re-map back-office stack off Paul before start","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s06","name":"Russian onboarding — pay $5k relocation bonus; offer letter and start date to Paul","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s07","name":"Mark Roby — set up case study","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s08","name":"Adam — send one-month consultant extension, then decide on full time","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s09","name":"RBN Associate — confirm job posting is live","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s10","name":"Menachem — define engagement scope (ties to Dominance MMA)","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v69s11","name":"Laptop and phone set-up — consolidate the two Asana projects","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v70', $json${"gid":"v70","name":"Data Project","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"Overdue since 2 Sep · one outcome, no single owner","order":70,"subtasks":[{"gid":"v70s01","name":"Set a firm LIVE date","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v70s02","name":"Adam to present the final product","assignee":"Adam","horizon":"vault","dueDate":null,"done":false},{"gid":"v70s03","name":"Define Thomas's role vs royalty database project","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v70s04","name":"Reproduce Q1 reporting in the database","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v70s05","name":"Name a single owner for the whole outcome","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v71', $json${"gid":"v71","name":"Nexus transition","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"Q3 strategic priority","order":71,"subtasks":[{"gid":"v71s01","name":"Complete Nexus transition","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v71s02","name":"Stand-up items — emails, Claude, Asana set-up","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v71s03","name":"Revenue build-out / Nexus rev planning — name owner and date","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v71s04","name":"Landing page on website","assignee":"Adam","horizon":"vault","dueDate":null,"done":false},{"gid":"v71s05","name":"MMM Nexus Operations Strategy (overdue since 17 Jul; blocking)","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v71s06","name":"Scope Nexus tech stack: royalty DB, portal credentials, ingestion templates, social harvester","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v72', $json${"gid":"v72","name":"Team economics","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"","order":72,"subtasks":[{"gid":"v72s01","name":"Base comp and 2026 comp adjustments — clear answer","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v72s02","name":"Carry allocation and vesting","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v72s03","name":"SLP documentation — South Park and Pineapple (F2, F3, Pineapple entities)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v73', $json${"gid":"v73","name":"Reporting","lead":"Paul","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"","order":73,"subtasks":[{"gid":"v73s01","name":"Q2 fund deliverables — publish quarterly close schedule","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v73s02","name":"Q2 portco deliverables","assignee":"Tatiana","horizon":"vault","dueDate":null,"done":false},{"gid":"v73s03","name":"Q2 closes per entity — Fund II, HoldCo I, 5X, MMM 2.0, ProducerCo, Marshmello (71 of 72 open)","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v73s04","name":"Valuation committee sign-off — F3, Pineapple, F1, Prendi, NL, Spark","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v73s05","name":"Royalty database project","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v73s06","name":"Contract folder system","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v73s07","name":"PG memos — identify owner and deliverable","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v73s08","name":"SP reporting with PG","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v73s09","name":"Consolidate all PG threads under one owner","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v74', $json${"gid":"v74","name":"Fundraising & capital structure","lead":"Victor","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"Eight parallel items · needs one written status","order":74,"subtasks":[{"gid":"v74s01","name":"Close $100M US money","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v74s02","name":"Fund III credit facility and sublines","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v74s03","name":"CDPQ co-invest vehicle","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v74s04","name":"iCAV set-up (merge with ICAV Q3 planning record)","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v74s05","name":"RBN Co set-up","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v74s06","name":"Songs of Spirit line of credit","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v74s07","name":"Repay Weeknd warehouse (confirm whether same facility as Iconiq)","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v74s08","name":"F2 securitization rating — decide together with Fund II sale question","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v74s09","name":"Written consolidated status from Victor","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v75', $json${"gid":"v75","name":"LP & investor relations","lead":"","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"Live fundraise · six items, no owner","order":75,"subtasks":[{"gid":"v75s01","name":"Aksia — valuation question","assignee":"","horizon":"vault","dueDate":"2026-09-30","done":false},{"gid":"v75s02","name":"Aksia — ask whether GIC wants a $10M bite in Pineapple","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v75s03","name":"NM (NMERB) — complete fundraise charts","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v75s04","name":"NM (NMERB) — respond to LPA comments","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v75s05","name":"MS — send fundraising email","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v75s06","name":"Pineapple co-invest LP consent (sequence with CDPQ vehicle)","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v75s07","name":"Assign one owner for all LP items; standing LP status line in partner review","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v76', $json${"gid":"v76","name":"Back office","lead":"Paul","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"","order":76,"subtasks":[{"gid":"v76s01","name":"Mgmt co 2026 budget, cost share and reporting process (reconcile owner: Paul vs Rich)","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v76s02","name":"ACA compliance mock audit","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v76s03","name":"Bind insurance — GPL, cyber, CHS","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v76s04","name":"2025 tax returns — funds","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v76s05","name":"2025 tax returns — portcos","assignee":"Tatiana","horizon":"vault","dueDate":null,"done":false},{"gid":"v76s06","name":"AP process with business approval and wire release — funds and portcos","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v76s07","name":"Ramp T&E launch — policy update and training (overdue since 10 Jul)","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v77', $json${"gid":"v77","name":"Cash planning","lead":"","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"","order":77,"subtasks":[{"gid":"v77s01","name":"F2 dividends — MC","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v77s02","name":"F2 dividends — HoldCo 1","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v77s03","name":"F2 dividends — MMM 1.0","assignee":"Abe","horizon":"vault","dueDate":null,"done":false},{"gid":"v77s04","name":"Prendi sale distribution","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v77s05","name":"NL SMA sale distribution / excess reserve","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v77s06","name":"HoldCo dividend recommendation (overdue since 3 Jul)","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v78', $json${"gid":"v78","name":"Operating infrastructure","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"","order":78,"subtasks":[{"gid":"v78s01","name":"Consolidated Entity Registry — 88 entities, all open","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v78s02","name":"Portal logins and credentials — consolidate seven legacy projects (42 of 43 open)","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v78s03","name":"Operating Calendar — set owners and recurrence (12 of 14 open)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v78s04","name":"Lyric New Deal Onboarding Template — first run (33 tasks)","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v78s05","name":"Ingestion template creation (Master Tracker)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v79', $json${"gid":"v79","name":"Songs of Spirit & Nashville","lead":"","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"","order":79,"subtasks":[{"gid":"v79s01","name":"Define Thomas's SoS mandate before the Nashville trip","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v79s02","name":"Assign owners to unassigned SoS deals (Tkay, Will Jay, Mota, Taydex, Rubin, Montana)","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v79s03","name":"Nashville training camp — confirm December or drop","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v80', $json${"gid":"v80","name":"Fund II sale","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"No workstream yet — decide if live","order":80,"subtasks":[{"gid":"v80s01","name":"Decide whether Fund II sale is live","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v80s02","name":"If live: stand up workstream — banker track, data room, LP consent analysis, rating decision","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v80s03","name":"If not live: kill the F2 securitization rating task","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v81', $json${"gid":"v81","name":"Other firm items","lead":"","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"note":"","order":81,"subtasks":[{"gid":"v81s01","name":"Frank contract — 7% admin plus 15% procured","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v81s02","name":"Eaton agreement — respond with Weil markup; confirm LP vs commercial counterparty","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v81s03","name":"Alan's side projects (cartoon, music video IP) — decide firm involvement","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v81s04","name":"The House — define the deliverable","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v81s05","name":"Austin Rosen — re-engage or close out formally","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v81s06","name":"AGM 2026 — plan, date and owner","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v81s07","name":"MMM 2.0 — decide firm time allocation this quarter (Dave Jordan)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.meta (key, data) values ('team', $json${"people":["Abe","Adam","Mason","Paul","Rich","Ross","Tatiana","Thomas","Victor","Vinny"],"emails":{"Rich":"rgarzia@lyriccapitalgroup.com","Ross":"rcameron@lyriccapitalgroup.com","Vinny":"vdevalapalli@lyriccapitalgroup.com"}}$json$::jsonb) on conflict (key) do update set data = excluded.data;
insert into public.meta (key, data) values ('ooo', $json${"entries":[]}$json$::jsonb) on conflict (key) do update set data = excluded.data;
insert into public.meta (key, data) values ('review', $json${"overrides":{}}$json$::jsonb) on conflict (key) do update set data = excluded.data;
insert into public.meta (key, data) values ('labels', $json${"labels":{"col_assigned":"Task Assignee","col_main":"Project","col_mainlead":"Main Project Lead","col_mainpriority":"Project Timeline","col_priority":"Task Timeline","mcol_due":"Project Due Date","mcol_lead":"Project Lead","mcol_name":"Project","mcol_priority":"Timeline","tab_summary":"Chief View"}}$json$::jsonb) on conflict (key) do update set data = excluded.data;
