-- Lyric Flow — Lyric Capital Group firm priorities dashboard
-- Run this once in Supabase: SQL Editor -> New query -> paste -> Run.

-- ============ tables ============
create table if not exists public.tasks (
  id text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.meta (
  key text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  person text
);

-- keep updated_at fresh
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists tasks_touch on public.tasks;
create trigger tasks_touch before update on public.tasks for each row execute function public.touch_updated_at();
drop trigger if exists meta_touch on public.meta;
create trigger meta_touch before update on public.meta for each row execute function public.touch_updated_at();

-- ============ row-level security ============
-- Only signed-in users can read or write anything. Sign-ups are created by
-- you in the Supabase console, so "authenticated" = your approved people.
alter table public.tasks enable row level security;
alter table public.meta enable row level security;
alter table public.profiles enable row level security;

drop policy if exists tasks_rw on public.tasks;
create policy tasks_rw on public.tasks for all to authenticated using (true) with check (true);
drop policy if exists meta_rw on public.meta;
create policy meta_rw on public.meta for all to authenticated using (true) with check (true);
drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ============ live sync ============
alter publication supabase_realtime add table public.tasks;
alter publication supabase_realtime add table public.meta;

-- ============ seed: Vault loaded from the 28 Sep 2026 Priority Register ============
insert into public.tasks (id, data) values ('v01', $json${"gid":"v01","name":"Alesso","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":1,"subtasks":[{"gid":"v01s01","name":"Confirm closing (reported closing Thursday; overdue since 18 Sep) and clear","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v02', $json${"gid":"v02","name":"Tkay (Songs of Spirit)","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":2,"subtasks":[{"gid":"v02s01","name":"Assign owner and drive to close (longform)","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v03', $json${"gid":"v03","name":"Will Jay (Songs of Spirit)","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":3,"subtasks":[{"gid":"v03s01","name":"Assign owner and drive to close ($275k advance with flowthrough)","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v04', $json${"gid":"v04","name":"Project Ecosystem","lead":"Vinny","horizon":"vault","group":"Deals","dueDate":"2026-10-24","followUp":[],"order":4,"subtasks":[{"gid":"v04s01","name":"Run diligence to close — Priority #1","assignee":"Vinny","horizon":"vault","dueDate":"2026-10-24","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v05', $json${"gid":"v05","name":"All American Rejects","lead":"Abe","horizon":"vault","group":"Deals","dueDate":"2026-09-30","followUp":[],"order":5,"subtasks":[{"gid":"v05s01","name":"Respond to band on creative structure request","assignee":"Abe","horizon":"vault","dueDate":"2026-09-30","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v06', $json${"gid":"v06","name":"Playboi Carti","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":6,"subtasks":[{"gid":"v06s01","name":"Get LOI out ($50M+)","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v06s02","name":"Resolve status conflict on the board","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v07', $json${"gid":"v07","name":"Jonathan Cain (Journey)","lead":"Abe","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":7,"subtasks":[{"gid":"v07s01","name":"Confirm 23 Sep completion was a close, not a pass","assignee":"Abe","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v08', $json${"gid":"v08","name":"Howe","lead":"Victor","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":8,"subtasks":[{"gid":"v08s01","name":"RBN structure — monitor; nothing actionable at present","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v09', $json${"gid":"v09","name":"Angelo Mota / Taydex / Coleton Rubin (SoS)","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":9,"subtasks":[{"gid":"v09s01","name":"Assign owner — Angelo Mota","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v09s02","name":"Assign owner — Taydex","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v09s03","name":"Assign owner — Coleton Rubin","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v10', $json${"gid":"v10","name":"Southside","lead":"Abe","horizon":"vault","group":"Deals","dueDate":"2026-10-02","followUp":[],"order":10,"subtasks":[{"gid":"v10s01","name":"Finish one-pager","assignee":"Abe","horizon":"vault","dueDate":null,"done":false},{"gid":"v10s02","name":"Get overdue LOI to seller by Friday","assignee":"Abe","horizon":"vault","dueDate":"2026-10-02","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v11', $json${"gid":"v11","name":"Aerosmith","lead":"Abe","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":11,"subtasks":[{"gid":"v11s01","name":"Chase LOI from RS — this-week priority","assignee":"Abe","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v12', $json${"gid":"v12","name":"Lil Baby","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":12,"subtasks":[{"gid":"v12s01","name":"Next step after one-pager ($50M+)","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v12s02","name":"Resolve status conflict on the board","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v13', $json${"gid":"v13","name":"Tommy Brown","lead":"Abe","horizon":"vault","group":"Deals","dueDate":"2026-11-01","followUp":[],"order":13,"subtasks":[{"gid":"v13s01","name":"Diary: engage after existing LOI expires 31 Oct","assignee":"Abe","horizon":"vault","dueDate":"2026-11-01","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v14', $json${"gid":"v14","name":"Empire (Ghazi)","lead":"Victor","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":14,"subtasks":[{"gid":"v14s01","name":"Progress LOI","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v15', $json${"gid":"v15","name":"CRM (Neil Gillis)","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":15,"subtasks":[{"gid":"v15s01","name":"Structure discussion with PG","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v16', $json${"gid":"v16","name":"Randy Montana","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":16,"subtasks":[{"gid":"v16s01","name":"Chase both offers (Lyric and SoS) out 15 Sep","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v17', $json${"gid":"v17","name":"LOI stage — unassigned","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":17,"subtasks":[{"gid":"v17s01","name":"Assign owner — Tim McGraw","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v17s02","name":"Assign owner — Nic Hooper","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v17s03","name":"Assign owner — Gustavo Santaolalla","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v17s04","name":"Assign owner — Five Finger Death Punch","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v17s05","name":"Assign owner — Derek George","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v17s06","name":"Assign owner — Ratchopper","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v18', $json${"gid":"v18","name":"MMM 2.0 pipeline names","lead":"Abe","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":18,"subtasks":[{"gid":"v18s01","name":"Decide MMM 2.0 time allocation (unblocks all names below)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v18s02","name":"Noam Daniel / Jeremy Zag — assign or park","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v18s03","name":"Paw Patrol — assign or park","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v18s04","name":"Guillaume Roussel — assign or park","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v18s05","name":"Christophe Beck — assign or park","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v18s06","name":"James Gibb sourced — follow up","assignee":"Abe","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v19', $json${"gid":"v19","name":"Dominance MMA","lead":"Victor","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":19,"subtasks":[{"gid":"v19s01","name":"Staff Menachem for remaining work this week, or move to Passed","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v20', $json${"gid":"v20","name":"Jim Alexander","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":20,"subtasks":[{"gid":"v20s01","name":"Progress term sheet (Frank met the UK team)","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v21', $json${"gid":"v21","name":"Johnny Valentine","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":21,"subtasks":[{"gid":"v21s01","name":"Close out term sheet back-and-forth","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v22', $json${"gid":"v22","name":"Federation Studio / Rupert Parkes / Graeme Revell (MMM)","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":22,"subtasks":[{"gid":"v22s01","name":"Review model — assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v23', $json${"gid":"v23","name":"Daniel Ross","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":23,"subtasks":[{"gid":"v23s01","name":"Assign owner","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v24', $json${"gid":"v24","name":"Martin Garrix","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":24,"subtasks":[{"gid":"v24s01","name":"Get remaining data from Martin's father","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v24s02","name":"Prepare two offers: catalogue buyout and 360 structure","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v25', $json${"gid":"v25","name":"Tape Room (Ashley Gorley)","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":"2026-09-29","followUp":[],"order":25,"subtasks":[{"gid":"v25s01","name":"Prepare for ShotTower process — offer expected mid-October","assignee":"Thomas","horizon":"vault","dueDate":"2026-09-29","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v26', $json${"gid":"v26","name":"Benson Boone","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":26,"subtasks":[{"gid":"v26s01","name":"Obtain statement data from sellers","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v27', $json${"gid":"v27","name":"Bert Burns / Roberto Carlos / John Shanks","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":27,"subtasks":[{"gid":"v27s01","name":"Model underway — assign owners","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v28', $json${"gid":"v28","name":"Dominic Fike","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":28,"subtasks":[{"gid":"v28s01","name":"Deliver one-pager (overdue since 23 Sep)","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v28s02","name":"Collect Sony JV statement at month end","assignee":"Thomas","horizon":"vault","dueDate":"2026-09-30","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v29', $json${"gid":"v29","name":"Imagine Dragons","lead":"Ross","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":29,"subtasks":[{"gid":"v29s01","name":"Restart one-pager and data request ($50M+ RBN/equity; drifting since 31 Jul)","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v30', $json${"gid":"v30","name":"David Guetta","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":30,"subtasks":[{"gid":"v30s01","name":"Chase diligence materials ($50M+)","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v31', $json${"gid":"v31","name":"Fairuz","lead":"Victor","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":31,"subtasks":[{"gid":"v31s01","name":"Speak to sellers; Raine running process","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v32', $json${"gid":"v32","name":"Future","lead":"Abe","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":32,"subtasks":[{"gid":"v32s01","name":"Complete one-pager from incomplete data room","assignee":"Abe","horizon":"vault","dueDate":null,"done":false},{"gid":"v32s02","name":"Call with Future's mother","assignee":"Abe","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v33', $json${"gid":"v33","name":"London on Da Track","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":33,"subtasks":[{"gid":"v33s01","name":"Staff it or park it explicitly","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v33s02","name":"Start income summary from received data","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v34', $json${"gid":"v34","name":"Mike Dean","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":34,"subtasks":[{"gid":"v34s01","name":"Assign owner","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v34s02","name":"Data room expected this week — review on arrival","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v35', $json${"gid":"v35","name":"Black River / Ballerini","lead":"Thomas","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":35,"subtasks":[{"gid":"v35s01","name":"Big Loud partnership approach","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v35s02","name":"De-duplicate the three board records","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v36', $json${"gid":"v36","name":"Top Dawg Entertainment","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":36,"subtasks":[{"gid":"v36s01","name":"NDA stage — assign owner","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v37', $json${"gid":"v37","name":"UAM (Universal Arabic Music)","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":37,"subtasks":[{"gid":"v37s01","name":"No action until data arrives — ramp candidate","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v38', $json${"gid":"v38","name":"Buffalo Bills","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":38,"subtasks":[{"gid":"v38s01","name":"Await NDA signature; create deal record","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v39', $json${"gid":"v39","name":"Live Nation Merchandising","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":39,"subtasks":[{"gid":"v39s01","name":"Game plan before Matt Hansen call (note SalxCo adjacency)","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v39s02","name":"Schedule Matt Hansen call","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v40', $json${"gid":"v40","name":"Pulse","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":40,"subtasks":[{"gid":"v40s01","name":"Set direction","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v41', $json${"gid":"v41","name":"One-pager stage — unassigned","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":41,"subtasks":[{"gid":"v41s01","name":"Assign owner — The Shalizi Group","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v41s02","name":"Assign owner — Koe Wetzel","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v41s03","name":"Assign owner — Wu Tang Clan","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v42', $json${"gid":"v42","name":"Awaiting diligence — unassigned","lead":"","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":42,"subtasks":[{"gid":"v42s01","name":"Assign owner — Travis Scott","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v42s02","name":"Assign owner — Chief Keef","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v42s03","name":"Assign owner — Swedish House Mafia","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v42s04","name":"Assign owner — John Williams","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v42s05","name":"Assign owner — Toby McKeehan","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v42s06","name":"Assign owner — Big Noise","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v42s07","name":"Assign owner — Rezonate","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v43', $json${"gid":"v43","name":"Pipeline hygiene / kill candidates","lead":"Vinny","horizon":"vault","group":"Deals","dueDate":null,"followUp":[],"order":43,"subtasks":[{"gid":"v43s01","name":"United Masters — decide, then archive both duplicate records","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v43s02","name":"Ink Entertainment — send the kill note","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v43s03","name":"'Deal Identified' backlog (~40 names) — archive or set review dates","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v44', $json${"gid":"v44","name":"SalxCo / YCFU — RC critical path","lead":"Ross","horizon":"vault","group":"Deals","dueDate":"2026-10-15","followUp":[],"order":44,"subtasks":[{"gid":"v44s01","name":"RBN / debt financing structure (run bridge loan as the same item)","assignee":"Ross","horizon":"vault","dueDate":"2026-10-09","done":false},{"gid":"v44s02","name":"Third-party partnerships — Live Nation reorg + documentation","assignee":"Ross","horizon":"vault","dueDate":"2026-10-14","done":false},{"gid":"v44s03","name":"Contracts operating outside of term — Weeknd/Brandy/Metro memorialisation","assignee":"Ross","horizon":"vault","dueDate":"2026-10-14","done":false},{"gid":"v44s04","name":"Draft management agreements for potential signings (Young Thug, Future, Rema, M.I.A.)","assignee":"Ross","horizon":"vault","dueDate":"2026-10-14","done":false},{"gid":"v44s05","name":"Artist contract diligence","assignee":"Ross","horizon":"vault","dueDate":"2026-10-15","done":false},{"gid":"v44s06","name":"Pre-closing reorganization legal & tax sign-off","assignee":"Abe","horizon":"vault","dueDate":"2026-09-30","done":false},{"gid":"v44s07","name":"Employee & corporate structure chart (D&O list from GSM)","assignee":"Rich","horizon":"vault","dueDate":"2026-09-29","done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v45', $json${"gid":"v45","name":"Recruiting","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":45,"subtasks":[{"gid":"v45s01","name":"Senior Fund Accountant — agree Claude screening prompt (Rich/RC), then review 80 resumes","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s02","name":"FP&A Associate — resume review (same blocker)","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s03","name":"Analyst hire — set date and plan","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s04","name":"COO/CFO (Sean Pallen) — confirm offer letter status","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s05","name":"Sean Pallen — re-map back-office stack off Paul before start","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s06","name":"Russian onboarding — pay $5k relocation bonus; offer letter and start date to Paul","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s07","name":"Mark Roby — set up case study","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s08","name":"Adam — send one-month consultant extension, then decide on full time","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s09","name":"RBN Associate — confirm job posting is live","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s10","name":"Menachem — define engagement scope (ties to Dominance MMA)","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v45s11","name":"Laptop and phone set-up — consolidate the two Asana projects","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v46', $json${"gid":"v46","name":"Data Project","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":46,"subtasks":[{"gid":"v46s01","name":"Set a firm LIVE date (overdue since 2 Sep)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v46s02","name":"Adam to present the final product","assignee":"Adam","horizon":"vault","dueDate":null,"done":false},{"gid":"v46s03","name":"Define Thomas's role vs royalty database project","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v46s04","name":"Reproduce Q1 reporting in the database","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v46s05","name":"Name a single owner for the whole outcome","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v47', $json${"gid":"v47","name":"Nexus transition","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":47,"subtasks":[{"gid":"v47s01","name":"Complete Nexus transition (Q3 strategic priority)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v47s02","name":"Stand-up items — emails, Claude, Asana set-up","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v47s03","name":"Revenue build-out / Nexus rev planning — name owner and date","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v47s04","name":"Landing page on website","assignee":"Adam","horizon":"vault","dueDate":null,"done":false},{"gid":"v47s05","name":"MMM Nexus Operations Strategy (overdue since 17 Jul; blocking)","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v47s06","name":"Scope Nexus tech stack: royalty DB, portal credentials, ingestion templates, social harvester","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v48', $json${"gid":"v48","name":"Team economics","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":48,"subtasks":[{"gid":"v48s01","name":"Base comp and 2026 comp adjustments — clear answer","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v48s02","name":"Carry allocation and vesting","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v48s03","name":"SLP documentation — South Park and Pineapple (F2, F3, Pineapple entities)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v49', $json${"gid":"v49","name":"Reporting","lead":"Paul","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":49,"subtasks":[{"gid":"v49s01","name":"Q2 fund deliverables — publish quarterly close schedule","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v49s02","name":"Q2 portco deliverables","assignee":"Tatiana","horizon":"vault","dueDate":null,"done":false},{"gid":"v49s03","name":"Q2 closes per entity — Fund II, HoldCo I, 5X, MMM 2.0, ProducerCo, Marshmello (71 of 72 open)","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v49s04","name":"Valuation committee sign-off — F3, Pineapple, F1, Prendi, NL, Spark","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v49s05","name":"Royalty database project","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v49s06","name":"Contract folder system","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false},{"gid":"v49s07","name":"PG memos — identify owner and deliverable","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v49s08","name":"SP reporting with PG","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v49s09","name":"Consolidate all PG threads under one owner","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v50', $json${"gid":"v50","name":"Fundraising & capital structure","lead":"Victor","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":50,"subtasks":[{"gid":"v50s01","name":"Close $100M US money","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v50s02","name":"Fund III credit facility and sublines","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v50s03","name":"CDPQ co-invest vehicle","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v50s04","name":"iCAV set-up (merge with ICAV Q3 planning record)","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v50s05","name":"RBN Co set-up","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v50s06","name":"Songs of Spirit line of credit","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v50s07","name":"Repay Weeknd warehouse (confirm whether same facility as Iconiq)","assignee":"Victor","horizon":"vault","dueDate":null,"done":false},{"gid":"v50s08","name":"F2 securitization rating — decide together with Fund II sale question","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v50s09","name":"Written consolidated status from Victor","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v51', $json${"gid":"v51","name":"LP & investor relations","lead":"","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":51,"subtasks":[{"gid":"v51s01","name":"Aksia — valuation question","assignee":"","horizon":"vault","dueDate":"2026-09-30","done":false},{"gid":"v51s02","name":"Aksia — ask whether GIC wants a $10M bite in Pineapple","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v51s03","name":"NM (NMERB) — complete fundraise charts","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v51s04","name":"NM (NMERB) — respond to LPA comments","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v51s05","name":"MS — send fundraising email","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v51s06","name":"Pineapple co-invest LP consent (sequence with CDPQ vehicle)","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v51s07","name":"Assign one owner for all LP items; standing LP status line in partner review","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v52', $json${"gid":"v52","name":"Back office","lead":"Paul","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":52,"subtasks":[{"gid":"v52s01","name":"Mgmt co 2026 budget, cost share and reporting process (reconcile owner: Paul vs Rich)","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v52s02","name":"ACA compliance mock audit","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v52s03","name":"Bind insurance — GPL, cyber, CHS","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v52s04","name":"2025 tax returns — funds","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v52s05","name":"2025 tax returns — portcos","assignee":"Tatiana","horizon":"vault","dueDate":null,"done":false},{"gid":"v52s06","name":"AP process with business approval and wire release — funds and portcos","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v52s07","name":"Ramp T&E launch — policy update and training (overdue since 10 Jul)","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v53', $json${"gid":"v53","name":"Cash planning","lead":"","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":53,"subtasks":[{"gid":"v53s01","name":"F2 dividends — MC","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v53s02","name":"F2 dividends — HoldCo 1","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v53s03","name":"F2 dividends — MMM 1.0","assignee":"Abe","horizon":"vault","dueDate":null,"done":false},{"gid":"v53s04","name":"Prendi sale distribution","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v53s05","name":"NL SMA sale distribution / excess reserve","assignee":"Paul","horizon":"vault","dueDate":null,"done":false},{"gid":"v53s06","name":"HoldCo dividend recommendation (overdue since 3 Jul)","assignee":"Victor","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v54', $json${"gid":"v54","name":"Operating infrastructure","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":54,"subtasks":[{"gid":"v54s01","name":"Consolidated Entity Registry — 88 entities, all open","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v54s02","name":"Portal logins and credentials — consolidate seven legacy projects (42 of 43 open)","assignee":"Thomas","horizon":"vault","dueDate":null,"done":false},{"gid":"v54s03","name":"Operating Calendar — set owners and recurrence (12 of 14 open)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v54s04","name":"Lyric New Deal Onboarding Template — first run (33 tasks)","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v54s05","name":"Ingestion template creation (Master Tracker)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v55', $json${"gid":"v55","name":"Songs of Spirit & Nashville","lead":"","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":55,"subtasks":[{"gid":"v55s01","name":"Define Thomas's SoS mandate before the Nashville trip","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v55s02","name":"Assign owners to unassigned SoS deals (Tkay, Will Jay, Mota, Taydex, Rubin, Montana)","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v55s03","name":"Nashville training camp — confirm December or drop","assignee":"Vinny","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v56', $json${"gid":"v56","name":"Fund II sale","lead":"Ross","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":56,"subtasks":[{"gid":"v56s01","name":"Decide whether Fund II sale is live","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v56s02","name":"If live: stand up workstream — banker track, data room, LP consent analysis, rating decision","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v56s03","name":"If not live: kill the F2 securitization rating task","assignee":"","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.tasks (id, data) values ('v57', $json${"gid":"v57","name":"Other firm items","lead":"","horizon":"vault","group":"Operations & Firm Build","dueDate":null,"followUp":[],"order":57,"subtasks":[{"gid":"v57s01","name":"Frank contract — 7% admin plus 15% procured","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v57s02","name":"Eaton agreement — respond with Weil markup; confirm LP vs commercial counterparty","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v57s03","name":"Alan's side projects (cartoon, music video IP) — decide firm involvement","assignee":"Ross","horizon":"vault","dueDate":null,"done":false},{"gid":"v57s04","name":"The House — define the deliverable","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v57s05","name":"Austin Rosen — re-engage or close out formally","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v57s06","name":"AGM 2026 — plan, date and owner","assignee":"","horizon":"vault","dueDate":null,"done":false},{"gid":"v57s07","name":"MMM 2.0 — decide firm time allocation this quarter (Dave Jordan)","assignee":"Ross","horizon":"vault","dueDate":null,"done":false}]}$json$::jsonb) on conflict (id) do update set data = excluded.data;
insert into public.meta (key, data) values ('team', $json${"people":["Abe","Adam","Mason","Paul","Rich","Ross","Tatiana","Thomas","Victor","Vinny"],"emails":{"Rich":"rgarzia@lyriccapitalgroup.com","Ross":"rcameron@lyriccapitalgroup.com","Vinny":"vdevalapalli@lyriccapitalgroup.com"}}$json$::jsonb) on conflict (key) do update set data = excluded.data;
insert into public.meta (key, data) values ('ooo', $json${"entries":[]}$json$::jsonb) on conflict (key) do update set data = excluded.data;
insert into public.meta (key, data) values ('review', $json${"overrides":{}}$json$::jsonb) on conflict (key) do update set data = excluded.data;
insert into public.meta (key, data) values ('labels', $json${"labels":{"col_assigned":"Task Assignee","col_main":"Project","col_mainlead":"Main Project Lead","col_mainpriority":"Project Timeline","col_priority":"Task Timeline","mcol_due":"Project Due Date","mcol_lead":"Project Lead","mcol_name":"Project","mcol_priority":"Timeline","tab_summary":"Chief View"}}$json$::jsonb) on conflict (key) do update set data = excluded.data;
